#!/bin/sh

Package=$1

if [ "$Package" == "" ]; then

    if [ -f dist/doc/html/*/index.html ]; then
        $WEB_BROWSER dist/doc/html/*/index.html
    fi

else

    for d in `find $HOME/.cabal/share/doc -name index.html | grep $Package`
    do
        $WEB_BROWSER $d
    done

fi
